baseurl: ""
url: "https://carolinnesilva.com"

exclude:
  - CLAUDE.md
  - .github/
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - vendor/

brand_colors:
  lila: "#e3bbff"
  crema_gris: "#fcf2c8"
  azul_petroleo: "#4b4b66"
  rosado: "#f89cff"
  azul_rey: "#4646f2"

fonts:
  logo: "'Bytesized', sans-serif"
  titles: "'Overpass Mono', monospace"
  paragraphs: "'Space Grotesk', sans-serif"

# Menú configurable
navigation:
  - title: "INICIO"
    url: "/"
  - title: "PROYECTOS"
    url: "/proyectos/"
  - title: "INVESTIGACIÓN"
    url: "/investigacion/"
  - title: "PUBLICACIONES"
    url: "/publicaciones/"
  - title: "DIVULGACIÓN"
    url: "/divulgacion/"
  - title: "PERFIL DISEÑADORA"
    url: "/perfil-disenadora/"
  - title: "GALERÍA"
    url: "/galeria/"

collections:
  projects:
    output: true
    permalink: /proyectos/:path/

  investigacion:
    output: true
    permalink: /investigacion/:path/

  divulgacion:
    output: true
    permalink: /divulgacion/:path/

  experiencias:
    output: true
    permalink: /experiencias/:path/

  disenadora:
    output: true
    permalink: /perfil-disenadora/:path/

