services:
  blog:
    build: 
      context: .
    image: gh_jekyll/v1  # <--- AQUÍ defines el nombre y tag
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
          - .:/app
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling --baseurl ""